name: NPM Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type (patch, minor, major)'
        required: false
        default: ''

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Validate dispatch branch
        if: github.event_name == 'workflow_dispatch'
        run: |
          BRANCH="${GITHUB_REF##*/}"
          if [[ "$BRANCH" != "main" ]]; then
            echo "❌ Manual dispatch allowed only on 'main' branch. Current: $BRANCH"
            exit 1
          fi

      - name: Get commit message
        id: commit_message
        run: |
          COMMIT_MSG=$(git log -1 --pretty=format:%s || echo "")
          echo "message=$COMMIT_MSG" >> $GITHUB_OUTPUT

      - name: Install dependencies
        working-directory: ./src
        run: yarn install

      - name: Determine version bump type
        id: version_bump
        run: |
          INPUT_TYPE="${{ github.event.inputs.release_type }}"
          COMMIT_MSG="${{ steps.commit_message.outputs.message }}"

          if [[ "$INPUT_TYPE" != "" ]]; then
            case "$INPUT_TYPE" in
              patch|minor|major)
                echo "type=$INPUT_TYPE" >> $GITHUB_OUTPUT
                echo "pre=false" >> $GITHUB_OUTPUT
                ;;
              *)
                echo "❌ Invalid release_type input: '$INPUT_TYPE'"
                exit 1
                ;;
            esac
          elif [[ "$COMMIT_MSG" == *"[major]"* ]]; then
            echo "type=major" >> $GITHUB_OUTPUT
            echo "pre=false" >> $GITHUB_OUTPUT
          elif [[ "$COMMIT_MSG" == *"[minor]"* ]]; then
            echo "type=minor" >> $GITHUB_OUTPUT
            echo "pre=false" >> $GITHUB_OUTPUT
          elif [[ "$COMMIT_MSG" == *"[patch]"* ]]; then
            echo "type=patch" >> $GITHUB_OUTPUT
            echo "pre=false" >> $GITHUB_OUTPUT
          else
            echo "type=prerelease" >> $GITHUB_OUTPUT
            echo "pre=true" >> $GITHUB_OUTPUT
          fi

      - name: Run tests
        working-directory: ./src
        run: yarn test

      - name: Bump version
        working-directory: ./src
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          if [[ "${{ steps.version_bump.outputs.pre }}" == "true" ]]; then
            npm version prerelease --preid=beta -m "prerelease: %s [skip ci]"
          else
            npm version ${{ steps.version_bump.outputs.type }} -m "release: %s [skip ci]"
          fi

      - name: Get new version
        id: get_version
        working-directory: ./src
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build package
        working-directory: ./src
        run: yarn build

      - name: Publish to NPM
        working-directory: ./src
        run: |
          if [[ "${{ steps.version_bump.outputs.pre }}" == "true" ]]; then
            npm publish --access public --tag next
          else
            npm publish --access public
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push version changes
        run: |
          git push origin HEAD:main
          git push --tags

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Release v${{ steps.get_version.outputs.version }}
          body: |
            Automated release from commit:
            ${{ steps.commit_message.outputs.message }}
          prerelease: ${{ steps.version_bump.outputs.pre }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
